### ISSUE TITLE
How to get different colors in dripFill

### ISSUE THREAD

**Issue by lgellis** [daranzolin/d3rain#3]
Hi, I am loving this package!

I was simply hoping to change the dripFill parameter in the drip_style function.  It seems to accept nothing other than 'firebrick'.  I've tried 'black', 'green' passing in hex color codes and a number of other options.  Is there a list to choose from?

Thank you!

**Comment by daranzolin** [comment]
Hi! Ugh this was an oversight on my part and is now fixed in the latest commit. Try reinstalling!

**Comment by lgellis** [comment]
Worked like a charm!  Colors of all kinds, including hex codes!
